# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies without running scripts to avoid building twice if not needed
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Build the project
RUN npm run build

# Expose default port if needed (not specified, so not exposing a port)

# Command to run the MCP server
CMD [ "node", "dist/index.js" ]
